// ARC-11: all user-facing copy lives here. Wording matches PRD v1.0.
// Keep dynamic text as template functions `(args) => string`.

export const STRINGS = {
  common: {
    add: "Add",
    delete: "Delete",
    signOut: "Sign out",
    allTime: "All time",
    cancel: "Cancel",
    confirm: "Confirm",
    deleted: "Transaction deleted",
  },

  layout: {
    brand: "Tally",
    footer: "Tally does not provide financial advice. Your data stays on this device — back it up regularly.",
    dataUnreadableTitle: "Some of your stored data could not be read",
    dataUnreadableBody: "Your original data was left untouched on this device. Restore a backup or reset to recover.",
    dataUnreadableCta: "Open Settings",
  },

  sidebar: {
    subtitle: "Personal Expense Tracker",
    help: "Help",
    newTransaction: "New transaction",
  },

  dashboard: {
    title: "Dashboard",
    overview: (periodName) => `Overview for ${periodName}`,
    emptyTitle: "Add your first transaction",
    emptyBody:
      "Welcome to Tally. Record your first income or expense to get started. Your data lives on this device — back it up regularly from Settings.",
    emptyAdd: "Add transaction",
    totalIncome: "Total income",
    totalExpenses: "Total expenses",
    netPeriod: "Net this period",
    totalBalance: "Total balance",
    spendingByCategory: "Spending by category",
    reportsLink: "Reports",
    recent: "Recent",
    viewAll: "View all",
    noExpensesTitle: "No expenses in this period",
    noExpensesCounted: (n) => `${n} upcoming transaction${n > 1 ? "s" : ""} not counted yet.`,
    noExpensesEmpty: "Add an expense to see the breakdown.",
    noCountedTitle: "No counted transactions yet",
    noCountedBody: "Future-dated transactions appear once their date arrives.",
    upcomingBanner: (n) =>
      `${n} upcoming transaction${n > 1 ? "s are" : " is"} not counted yet. They'll appear in totals once their date arrives.`,
    toastDeleted: "Transaction deleted",
    toastDeletedBody: "Totals and charts updated.",
    deleteDialogTitle: "Delete this transaction?",
  },

  add: {
    title: "Add transaction",
    subtitle: "Record an income or expense. Future dates are saved as upcoming.",
    ready: "Ready to add",
    readyBody: "The form is open — fill in the details and save.",
    openForm: "Open form",
  },

  transactions: {
    title: "Transactions",
    count: (n, allTime) => `${n} record${n !== 1 ? "s" : ""}${allTime ? " · All time" : ""}`,
    exitAllTime: "Exit All time",
    searchPlaceholder: "Search note or category…",
    allTypes: "All types",
    typeIncome: "Income",
    typeExpense: "Expense",
    allCategories: "All categories",
    noMatchTitle: "No matching transactions",
    noMatchBody: "Try adjusting your search or filters.",
    clearFilters: "Clear filters",
    noTransactionsTitle: "No transactions yet",
    noTransactionsBody: "Add your first transaction to get started.",
    emptyAdd: "Add transaction",
    loadMore: (n) => `Load more (${n} remaining)`,
    upcomingTotal: (amount) => `Upcoming in this view: ${amount} — not counted in your balance.`,
    deleteDialogTitle: "Delete this transaction?",
  },

  reports: {
    title: "Reports",
    noCountedTitle: "No counted transactions in this period",
    noCountedBody:
      "Reports only include transactions dated today or earlier. Add a transaction or pick a different period.",
    totalSpending: "Total spending",
    totalIncome: "Total income",
    net: "Net",
    categoriesUsed: "Categories used",
    spendingByCategory: "Spending by category",
    incomeVsExpenses: "Income vs expenses",
    spendingTrend: (by) => `Spending trend ${by === "year" ? "(by month)" : "(by day)"}`,
    noExpenses: "No expenses recorded in this period.",
  },

  categories: {
    title: "Categories",
    subtitle: "Manage your expense categories. Income categories are fixed.",
    addHeading: "Add expense category",
    placeholder: "e.g. Pets, Subscriptions…",
    addHelp: "Up to 30 characters, unique among your expense categories.",
    expenseGroup: "Expense",
    incomeGroup: "Income",
    builtIn: "Built-in",
    fixedNote: "— fixed list, cannot be changed",
    txnCount: (n) => `${n} transaction${n !== 1 ? "s" : ""}`,
    addedToast: "Category added",
    renamedToast: "Category renamed",
    deletedToast: "Category deleted",
    movedToast: (n) => `${n} transaction${n !== 1 ? "s" : ""} moved to Other.`,
    deleteDialogTitle: "Delete this category?",
    deleteAndMove: "Delete & move to Other",
    movedWillMove: (n) => `${n} transaction${n !== 1 ? "s" : ""} will be moved to Other.`,
    ariaSave: "Save",
    ariaCancel: "Cancel",
    ariaRename: "Rename",
    ariaDelete: "Delete",
  },

  settings: {
    title: "Settings",
    subtitle: "Manage your preferences, data, and account.",
    currencyTitle: "Display currency",
    currencyBody: "A label only — amounts are never converted.",
    twoDecimals: "All amounts use two decimals.",
    categoriesTitle: "Categories",
    categoriesBody: "Add, rename, or delete custom expense categories.",
    backupTitle: "Backup & restore",
    backupBody: "Back up to a JSON file or restore by merging.",
    lastBackupLead: "Last backup:",
    never: "Never",
    backUp: "Back up my data",
    restore: "Restore from file",
    backupNote:
      "Backup files are plain, unencrypted JSON. Restore merges into your data and may bring back deleted transactions.",
    accountTitle: "Account",
    signOutHint: "Signing out keeps your data on this device.",
    resetTitle: "Reset all data",
    resetBody: "Permanently delete your transactions and custom categories.",
    resetButton: "Reset all data",
    helpTitle: "Help & privacy",
    helpBody: "How your data is stored and how to back up.",
    toastCurrency: "Display currency updated",
    toastCurrencyBody: "Amounts were relabelled, not converted.",
    toastBackup: "Backup downloaded",
    toastBackupBody: "Your JSON file is not encrypted — store it safely.",
    toastRestoreFailed: "Restore failed",
    toastRestoreComplete: "Restore complete",
    toastRestoreSummary: (added, skipped, updated) =>
      `${added} added, ${skipped} skipped${updated ? `, ${updated} updated` : ""}.`,
    toastNote: "Note",
    toastCurrencyKept: (currency) => `Backup used ${currency}. Your current currency was kept.`,
    toastReset: "All data reset",
    toastResetBody: "Your transactions and custom categories were removed.",
    currencyDialogTitle: "Change display currency?",
    currencyDialogLabel: "Change label",
    currencyDialogBody: (amount, currency) =>
      `This only changes the currency label. Existing amounts are <b>not converted</b> — ${amount} would simply be shown in ${currency}.`,
    restoreDialogTitle: "Restore this backup?",
    restoreDialogLabel: "Restore",
    restoreDialogLead: "This will <b>merge</b> into your current data:",
    restoreAdded: (n) => `${n} transaction${n !== 1 ? "s" : ""} added`,
    restoreSkipped: (n) => `${n} skipped (already exist)`,
    restoreUpdated: (n) => `${n} updated (newer version)`,
    restoreNote: "Transactions deleted since this backup will come back.",
    resetDialogTitle: "Reset all data?",
    resetDialogLabel: "Reset everything",
    resetDialogBody: (n, cats) =>
      `This permanently deletes ${n} transaction${n !== 1 ? "s" : ""} and ${cats} custom categor${cats !== 1 ? "ies" : "y"}. This cannot be undone.`,
    resetTypePrompt: `Type <span className="font-mono">RESET</span> to confirm:`,
    resetPlaceholder: "RESET",
  },

  help: {
    title: "Help & Privacy",
    subtitle: (name) => `Everything you need to know about how ${name} handles your data.`,
    deviceTitle: "Your data stays on this device",
    deviceBody:
      "{APP_NAME} stores all your transactions, categories, and settings in your browser only. Nothing is sent to a server, and the company cannot see your data. Data is kept separately for each account, so two people using the same browser never see each other's records.",
    browserTitle: "It lives in one browser",
    browserBody:
      "Because data is stored locally, clearing your browser's site data or switching devices will remove it. There is no cloud copy and no cross-device sync. That is why backups matter.",
    backupTitle: "Back up your data",
    backupBody:
      "Go to Settings and choose Back up my data. You'll get a JSON file with all your transactions, custom categories, and display currency. Keep it somewhere safe — it is not encrypted.",
    restoreTitle: "Restore from a backup",
    restoreBody:
      "In Settings, choose Restore and pick a backup file. Restore merges into your current data — it never replaces it. Transactions that already exist are skipped; if a transaction was deleted after the backup was made, restoring will bring it back.",
    adviceTitle: "No financial advice",
    adviceBody:
      "{APP_NAME} is a simple record-keeping tool. It does not provide financial, investment, or tax advice. The figures shown are calculated from the transactions you enter.",
    quickLinks: "Quick links",
    linkAdd: "Add a transaction",
    linkTransactions: "View & filter transactions",
    linkReports: "See your reports",
    linkSettings: "Back up or reset your data",
    backUpBold: "Back up my data",
    restoreBold: "Restore",
  },

  signIn: {
    brandSubtitle: "Sign in to {APP_NAME}",
    editorialTitle: "Track your money,<br />privately on this device.",
    editorialBody:
      "A clean, personal expense tracker for {DOMAIN} staff. Your income and expenses stay in your browser — no server, no company view.",
    privateToYou: "Private to you",
    onDeviceOnly: "On-device only",
    footer: "Tally does not provide financial advice.",
    signInGoogle: "Sign in with Google",
    signingIn: "Signing in…",
    onlyDomain: (domain) => `Only @${domain} accounts are admitted.`,
    back: "Back",
    chooseAccount: "Choose an account",
    continueTo: (name) => `to continue to ${name}`,
    useAnother: "Use another account",
    signInTitle: "Sign in",
    useDomain: (domain) => `Use your @${domain} account.`,
    fullName: "Full name",
    namePlaceholder: "Jane Doe",
    email: "Email",
    emailPlaceholder: (domain) => `you@${domain}`,
    signInButton: "Sign in",
    domainError: (domain) => `Only @${domain} accounts are allowed. Sign in with your company account.`,
  },

  form: {
    titleEdit: "Edit transaction",
    titleAdd: "Add transaction",
    expense: "Expense",
    income: "Income",
    amountLabel: "Amount",
    amountPlaceholder: "0.00",
    categoryLabel: "Category",
    dateLabel: "Date",
    noteLabel: "Note",
    noteOptional: "(optional)",
    notePlaceholder: "Add a short note",
    errType: "Choose a type.",
    errAmountRequired: "Amount is required.",
    errAmountFormat: "Enter a number with up to 2 decimals.",
    errAmountPositive: "Amount must be greater than zero.",
    errAmountLarge: "Amount is too large.",
    errCategory: "Choose a category.",
    errDate: "Date is required.",
    errNote: "Note must be 100 characters or fewer.",
    saveChanges: "Save changes",
    save: "Save",
    saveAndAnother: "Save & add another",
    toastUpdated: "Transaction updated",
    toastUpdatedBody: "Totals and charts refreshed.",
    toastSavedAnother: "Transaction saved",
    toastSavedAnotherBody: "Add another below.",
    toastSaved: "Transaction saved",
    toastSavedBody: "It now appears in your dashboard.",
  },

  row: {
    uncategorised: "Uncategorised",
    upcoming: "Upcoming",
    ariaEdit: "Edit",
    ariaDelete: "Delete",
  },

  period: {
    month: "Month",
    year: "Year",
    prev: "Previous period",
    next: "Next period",
  },

  backupReminder: {
    overdue: "It's been a while since your last backup.",
    never: "You have data but no backup yet.",
    livesHere: " Your data lives only on this device. ",
    backUpNow: "Back up now",
    dismiss: "Dismiss for 7 days",
  },
};